name: snowball
version: 0.1.0
author: Randy Merrill
description: A simple debt snowball scheduler.
dependencies:
  benchmark_harness: "1.0.4"
  browser: "0.10.0+2"
  js: "0.3.0"
  unittest: "0.11.0+5"
